### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by alljoyland** [suifei/asm2hex#2]
1 make lib ok
2 make build error

compile error log as below:

MINGW64 /d/code_test/asm2hex-1.2.0
$ make build
# **github.com/suifei/asm2hex/bindings/capstone**
**_bindings\capstone\capstone.go:181:61_**: **cannot use _Ctype_ulong(value) (value of type _Ctype_ulong) as
 _Ctype_ulonglong value in argument to (_Cfunc_cs_option)**
# github.com/go-gl/glfw/v3.3/glfw
cgo-gcc-prolog: In function '_cgo_54e84f7ae3fd_Cfunc_glfwSetErrorCallbackCB':
cgo-gcc-prolog:49:49: warning: unused variable '_cgo_a' [-Wunused-variable]
# github.com/go-gl/glfw/v3.3/glfw
cgo-gcc-prolog: In function '_cgo_54e84f7ae3fd_Cfunc_glfwTerminate':
cgo-gcc-prolog:142:49: warning: unused variable '_cgo_a' [-Wunused-variable]
# github.com/go-gl/glfw/v3.3/glfw
cgo-gcc-prolog: In function '_cgo_54e84f7ae3fd_Cfunc_glfwSetJoystickCallbackCB':
cgo-gcc-prolog:729:49: warning: unused variable '_cgo_a' [-Wunused-variable]
# github.com/go-gl/glfw/v3.3/glfw
cgo-gcc-prolog: In function '_cgo_54e84f7ae3fd_Cfunc_glfwSetMonitorCallbackCB':
cgo-gcc-prolog:354:49: warning: unused variable '_cgo_a' [-Wunused-variable]
# github.com/go-gl/glfw/v3.3/glfw
cgo-gcc-prolog: In function '_cgo_54e84f7ae3fd_Cfunc_glfwDefaultWindowHints':
cgo-gcc-prolog:71:49: warning: unused variable '_cgo_a' [-Wunused-variable]
cgo-gcc-prolog: In function '_cgo_54e84f7ae3fd_Cfunc_glfwPollEvents':
cgo-gcc-prolog:291:49: warning: unused variable '_cgo_a' [-Wunused-variable]
cgo-gcc-prolog: In function '_cgo_54e84f7ae3fd_Cfunc_glfwPostEmptyEvent':
cgo-gcc-prolog:303:49: warning: unused variable '_cgo_a' [-Wunused-variable]
cgo-gcc-prolog: In function '_cgo_54e84f7ae3fd_Cfunc_glfwWaitEvents':
cgo-gcc-prolog:790:49: warning: unused variable '_cgo_a' [-Wunused-variable]

error building application: exit status 1
make: *** [Makefile:88: build] Error 1

**Comment by alljoyland** [comment]
I have change the 181 line C.ulong to C.ulonglong is ok now. (win 10, amd64)

func (e *Engine) Option(opt_type OptionType, value OptionValue) error {
	if cserr := C.cs_option(e.handle, C.cs_opt_type(opt_type), C.ulonglong(value)); cserr != C.CS_ERR_OK {
		return CsError(cserr)
	}
	return nil
}

**Comment by suifei** [comment]
Important Notes:

1. Please use our provided msys64 build environment:
   https://github.com/suifei/asm2hex/releases/download/v1.1/msys64.7z

2. Why use this version:
   - Includes pre-compiled keystone and capstone static libraries
   - Avoids compatibility issues with Go bindings and CGO
   - V2 version rewritten in C++ offers better compatibility and performance
   - Tested and confirmed working on Windows 7 and above
   - Supports more Windows versions compared to fyne-based versions

3. Installation and Build Instructions:
   a) Extract msys64.7z to the root of your D drive
   b) Launch the build environment by running D:\msys64\mingw64.exe
   c) Navigate to your source code directory in the command line, for example:
      cd /d/works/asm2hex/
   d) Build process:
      - First, compile the libraries: make lib
      - Then build the main program: make build
      
---

重要说明：

1. 请务必使用我们提供的 msys64 编译环境：
   https://github.com/suifei/asm2hex/releases/download/v1.1/msys64.7z

2. 为什么要使用此版本：
   - 内含预编译的 keystone、capstone 静态库
   - 避免了 Go binding 和 CGO 的各种兼容性问题
   - C++ 重写的 v2 版本具有更好的兼容性和性能
   - 已通过 Windows 7 及以上系统的兼容性测试
   - 相比基于 fyne 库的版本，支持更多 Windows 版本

3. 安装与编译步骤：
   a) 将下载的 msys64.7z 解压到 D 盘根目录
   b) 运行 D:\msys64\mingw64.exe 启动编译环境
   c) 在命令行中切换到源代码目录，例如：
      cd /d/works/asm2hex/
   d) 编译过程：
      - 首先编译库文件：make lib
      - 然后构建主程序：make build

**Comment by suifei** [comment]
[https://github.com/suifei/asm2hex2](https://github.com/suifei/asm2hex2)

**Comment by alljoyland** [comment]
Thank you very much for your reply and the detail guide for compile
